csv = read.csv("C:/Users/HP/Downloads/Weather data.csv", as.is=T)
names(csv)
range(csv$DATE)
library(xts)
install.packages("tsbox")
library(tsbox)
historical = xts(csv[,c("TMAX","TMIN","PRCP")], order.by=as.Date(csv$DATE))
historical = ts_regular(historical)
historical = na.fill(historical, "extend")
historical = window(historical, start=as.Date("2000-01-01"), end=as.Date("2020-12-31"))
plot(ts_ts(historical$TMAX), col="darkred", bty="n", las=1, fg=NA, 
     ylim=c(-20, 120), ylab="Temperature (F)")
lines(ts_ts(historical$TMIN), col="navy")
grid(nx=NA, ny=NULL, lty=1, col="gray")
legend("topright", fill=c("darkred", "navy"), cex=0.7,
       legend=c("TMAX", "TMIN"), bg="white")
barplot(historical$PRCP, border=NA, col="darkgreen", ylim=c(0, 2),
        space=0, bty="n", las=1, fg=NA, ylab="Daily Rainfall (inches)")
grid(nx=NA, ny=NULL, lty=1)
summary(historical)
historical[historical$TMIN == min(historical$TMIN)]
historical[historical$TMAX == max(historical$TMAX)]
historical[historical$PRCP == max(historical$PRCP)]
historical$MONTH = format(index(historical), "%m")
months = split(as.numeric(historical$TMAX), historical$MONTH)
sapply(months, summary)
months = split(as.numeric(historical$TMIN), historical$MONTH)
sapply(months, summary)
decomposition = stl(ts_ts(historical$TMAX), s.window=365, t.window=7001)
plot(decomposition)
summary(decomposition$time.series[,"trend"])
decomposition = stl(ts_ts(historical$PRCP), s.window=365, t.window=7001)
plot(decomposition)
summary(decomposition$time.series[,"trend"])
monthly.tmax = period.apply(historical$TMAX, INDEX = seq(1, nrow(historical) - 1, 30.4375), FUN = mean)
plot(ts_ts(monthly.tmax), col="darkred", ylim=c(20, 100), 
     lwd=3, bty="n", las=1, fg=NA, ylab="TMAX (F)")
grid(nx=NA, ny=NULL, lty=1)
monthly.prcp = period.apply(historical$PRCP, INDEX = seq(1, nrow(historical) - 1, 30.4375), FUN = sum)
plot(ts_ts(monthly.prcp), col="darkgreen", 
     lwd=3, bty="n", las=1, fg=NA, ylab="Monthly Precipitation (inches)")
grid(nx=NA, ny=NULL, lty=1)
library(forecast)
training.data = period.apply(historical$TMAX, seq(1, nrow(historical) - 1, 30.4375), max)
model.tmax = hw(ts_ts(training.data), h=60)
plot(model.tmax, lwd=3, bty="n", las=1, fg=NA)
grid(nx=NA, ny=NULL, lty=1)
model.tmax = hw(ts_ts(training.data), h=720)
plot(model.tmax, lwd=3, bty="n", las=1, fg=NA)
grid(nx=NA, ny=NULL, lty=1)
training.data = ts_ts(historical$TMAX)
parameters = auto.arima(training.data)
print(parameters)
arima.model = arima(training.data, order = c(5,0,1), seasonal = list(order=c(0,1,0), period=365))
arima.tmax = forecast(arima.model, 1825)
plot(arima.tmax, lwd=3, bty="n", las=1, fg=NA, 
     xlim=c(2018, 2026), ylab="Mean Monthly High Temperature (F)")
grid(nx=NA, ny=NULL, lty=1)
